/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/Yoonje.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Yoonje.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.imagetostl_mesh0.geometry} material={materials.mat0} />
      <mesh geometry={nodes.imagetostl_mesh1.geometry} material={materials.mat1} />
      <mesh geometry={nodes.imagetostl_mesh2.geometry} material={materials.mat2} />
      <mesh geometry={nodes.imagetostl_mesh3.geometry} material={materials.mat3} />
      <mesh geometry={nodes.imagetostl_mesh4.geometry} material={materials.mat4} />
      <mesh geometry={nodes.imagetostl_mesh5.geometry} material={materials.mat5} />
    </group>
  )
}

useGLTF.preload('/Yoonje.glb')
