export const experience = [
  {
    company: 'Alterea, Inc.',
    role: 'Web Development Intern',
    period: 'Sep 2025 – Present',
    link: '',
    description: 'Building full-stack features and overhauling dashboard UI with React, TypeScript, and Firebase for a production web application.',
    bullets: [
      'Overhauled dashboard UI and multiple page layouts in React and TypeScript against Figma specs, establishing visual consistency across the entire application.',
      'Architected a typed user-role model with centralized role constants in TypeScript, eliminating brittle string-based permission checks and improving page performance by 31%.',
      'Engineered a reusable role-access hook abstracting permission logic into a single interface, reducing duplication across 10+ components.',
      'Shipped end-to-end Teacher Lesson Plan Quiz feature with React frontend and Firebase backend, driving personalized lesson plan generation from quiz responses.',
    ],
  },
  {
    company: 'Virginia Tech',
    role: 'Graduate Research Assistant — Data Analyst',
    period: 'Aug 2025 – Present',
    link: 'https://people.cs.vt.edu/sehrishbasir/research.html#ai-education',
    description: 'Investigating how LLM usage patterns correlate with student quiz performance to inform evidence-based educational AI research.',
    bullets: [
      'Consolidated 7 Canvas quiz CSV exports into unified per-student tables using Python and pandas, enabling cross-assignment performance comparison.',
      'Designed consent-aware ID mapping pipeline with deduplication and inner-join merging, producing exclusion reports for unmatched and non-consented records.',
      'Standardized raw exports via regex-based column renaming and schema normalization, ensuring reproducible and analysis-ready datasets.',
      'Delivered descriptive statistics and matplotlib/seaborn visualizations summarizing LLM usage frequency, verification methods, and prompt distributions.',
      'Ran ANOVA to surface statistically significant correlations between student scores and LLM usage, directly informing research conclusions on AI tool effectiveness.',
    ],
  },
  {
    company: 'Virginia Tech',
    role: 'Graduate Research Assistant — DBWorkout',
    period: 'Aug 2025 – Present',
    link: 'https://people.cs.vt.edu/sehrishbasir/research.html#dbworkout',
    description: 'Developing LLM-powered Flask APIs and UI components for an educational database practice platform with automated task and schema generation.',
    bullets: [
      'Validated course API endpoints via Postman across student and professor roles, verifying authentication flows and role-based access control.',
      'Built automated task generation API integrating OpenAI GPT with JSON schema validation, guaranteeing structured and consistent LLM output.',
      'Developed companion schema generation API enabling students to practice against LLM-created database structures tailored to course content.',
      'Iterated on prompt engineering strategies to measurably improve accuracy, depth, and relevance of generated tasks and schemas.',
      'Designed and implemented responsive UI for task and schema creation workflows, streamlining the content generation experience for instructors.',
    ],
  },
  {
    company: 'Virginia Tech',
    role: 'Graduate Research Assistant — Classroom Evaluation',
    period: 'Aug 2025 – Present',
    link: 'https://people.cs.vt.edu/sehrishbasir/research.html#classroom-eval',
    description: 'Building analytical dashboards and evaluation frameworks to study student engagement through gaze, posture, and LLM-derived signals from classroom video.',
    bullets: [
      'Conducted weekly literature reviews over 8 weeks to ground evaluation metrics in established classroom engagement and learning analytics research.',
      'Designed a multi-signal analytics framework fusing gaze detection, OpenPose posture classification, and LLM prompt outputs from live classroom video.',
      'Built interactive React dashboards with Recharts featuring average engagement time-series plots, enabling session-level trend analysis.',
      'Implemented stacked, color-coded histograms of gaze and posture distributions over time, surfacing engagement patterns interpretable by non-technical researchers.',
    ],
  },
  {
    company: 'Versy (Versy Talks)',
    role: 'Software Engineer Intern',
    period: 'May 2024 – Aug 2024',
    link: 'https://www.versytalks.com',
    description: 'Engineered real-time notification systems, authentication flows, and UI improvements across a production platform built on Next.js and PostgreSQL.',
    bullets: [
      'Designed and shipped a real-time notification system backed by PostgreSQL, building 10+ REST API endpoints to power in-app alerts.',
      'Redesigned the blog interface with Tailwind CSS, introducing responsive layout patterns and a refactored component architecture.',
      'Architected automated email-based password recovery using Prisma and PostgreSQL, replacing a manual reset process end-to-end.',
      'Applied Tailwind CSS responsive optimizations across key pages, improving mobile layout consistency and user engagement.',
      'Established reusable React component patterns and frontend design conventions adopted across the codebase.',
    ],
  },
  {
    company: 'Virginia Tech',
    role: 'Undergraduate Teaching Assistant',
    period: 'Aug 2023 – May 2025',
    link: '',
    description: 'Mentored 100+ students per semester across intro CS courses in C and Java; recognized for performance and promoted to Lead TA.',
    bullets: [
      'Supported students in Computer Organization (C) and Data Structures & Algorithms (Java) through concept walkthroughs, assignment guidance, and debugging sessions.',
      'Held 9 hours of weekly office hours each semester, directly assisting 100+ students with programming assignments and exam preparation.',
      'Proctored exams and upheld academic integrity procedures across large-enrollment courses.',
      'Elevated to Lead TA role in recognition of consistent performance, taking on coordination and escalation responsibilities for the TA team.',
    ],
  },
]